version: "3.9"

services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - "443:443"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app

volumes:
  static_volume:
  media_volume: