# STATUS_CHOICES VALUES
COMPLETE = 'COMPLETE'
PENDING_COMPLETE_DATA = 'PENDING_EXTRA_DATA'

# GENDER_CHOICES VALUES
MAN = 'MAN'
WOMAN = 'WOMAN'
NONE = 'NONE'

# CLOSET_CHOICES VALUES
FIRST_CLOSET = 1
SECOND_CLOSET = 2


STATUS_CHOICES = (
    (COMPLETE, 'Complete'),
    (PENDING_COMPLETE_DATA, 'Pending Complete Data'),
)


GENDER_CHOICES = (
    (MAN, 'Man'),
    (WOMAN, 'Woman'),
    (NONE, 'None'),
)


CLOSET_CHOICES = (
    (FIRST_CLOSET, 1),
    (SECOND_CLOSET, 2),
)
